CREATE TABLE IF NOT EXISTS admin(
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    passwordHash VARCHAR(255) NOT NULL,
    createdAtUTC TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updatedAtUTC TIMESTAMPTZ NOT NULL DEFAULT NOW()
);